apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: okp-solr-data
  labels:
    app.kubernetes.io/name: rhokp
    app.kubernetes.io/component: solr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
